### PR TITLE
Fix MQTT autoconf features

### PR DESCRIPTION
**Pull request by TheRealMoeder**
Fixes feature list for MQTT autoconf

### CODE REVIEW

**Comment by roflcoopter** [comment]
Home Assistant doesnt work anymore because of the change to ´´´return_to_base´´´ from ´´´return_home´´´. Shouldn't this PR be reversed or am i missing something?

**Comment by TheRealMoeder** [comment]
No expert on Home Assistant, but from what I read return_home is legacy and return_to_base is the new state scheme (
https://www.home-assistant.io/integrations/vacuum.mqtt/). You should check your HA configuration and probably rediscover the vacuum device

**Comment by Hypfer** [comment]
https://www.home-assistant.io/integrations/vacuum.mqtt/#legacy-basic-commands

`return_to_base` is legacy..

**Comment by TheRealMoeder** [comment]
Are you sure? From that page:

`State MQTT Protocol

The above configuration for this integration expects an MQTT protocol like the following.

STATE BASIC COMMANDS

MQTT topic: vacuum/command

Possible MQTT payloads:

start - Start cleaning
pause - Pause cleaning
return_to_base - Return to base/dock`

**Comment by roflcoopter** [comment]
I'm pretty sure. If you update to the latest home assistant version and rediscover the vacuum, it doesn't work with this PR.

**Comment by TheRealMoeder** [comment]
there seems to be an error in the HA documentation then, because the description differs from the configuration.yaml example for the State MQTT Protocol

**Comment by TheRealMoeder** [comment]
After reading the HA code the that is probably where the mess begins. It expects a feature „return_home“ in auto-discovery but actually sends a state „return_to_base“ via Mqtt. I wonder of this is intended...

**Pull request merged**
