### PR TITLE
init: Write a valetudo log file

### PR DESCRIPTION
**Pull request by cryptomilk**
Write output of valetudo to a log file.

### CODE REVIEW

**Comment by Hypfer** [comment]
Everything is already logged to `/var/log/upstart/valetudo.log` so I'm unsure if this change is necessary.

**Comment by cryptomilk** [comment]
Oh, I didn't know that.

**Comment by Hypfer** [comment]
Yeah we really need to document that somewhere

**Comment by cryptomilk** [comment]
We need this, as not everything lands in /var/log/upstart/valetudo.log

**Comment by Hypfer** [comment]
Can you give an example?

**Comment by cryptomilk** [comment]
Hmpft, my fault. I did not reset ...

**Pull request closed without merging**
