### PR TITLE
make virtual walls and forbidden zones user-configurable

### PR DESCRIPTION
**Pull request by rand256**
a bit stripped version of the same functionality from Valetudo RE fork separated from most customizations and tweaks of the mod

this one not tested on real hardware but hopefully should work

### CODE REVIEW

**Comment by bruvv** [comment]
What is the Valetudo RE fork you are talking about?

**Comment by rand256** [comment]
This one: https://github.com/rand256/valetudo
Was discussed on telegram channel.

**Comment by leonardpitzu** [comment]
hi. i adapted your PR to my code base. it works as expected but i have one question - is there a way to edit the wall/forbidden area?

**Comment by rand256** [comment]
It works just the same way as editing zones.

**Comment by Hypfer** [comment]
While this is already a huge improvement, I'd still prefer valetudo to save the no-go areas independently instead of just calling save_map, because there might be breakage.

Calling save_map should definitely trigger a map poll on the cloud interface, since closing the editor and opening it again is sometimes displaying stale data in my tests. I'll add that.

Anyways thank you for this PR. If you feel like it, I'd be glad to see the other valetudo-re features merged into master as well.

**Comment by Hypfer** [comment]
Sadly, I'm unable to delete no-go zones as well as virtual walls :/

**Pull request merged**
