### PR TITLE
add support for client certificate

### PR DESCRIPTION
**Pull request by mqtt-fan**

### CODE REVIEW

**Comment by Hypfer** [comment]
https://github.com/mqttjs/MQTT.js/

I can't seem to find that option in the library docs?

**Comment by mqtt-fan** [comment]
@Hypfer you can find it in the [tls client example](https://github.com/mqttjs/MQTT.js/blob/master/examples/tls%20client)/mqttclient.js or in the [pub.js](https://github.com/mqttjs/MQTT.js/blob/master/bin/pub.js) (line 85/89)

**Comment by Hypfer** [comment]
I see.
What about having the certificate in the configuration file? Since it's plain text, we could just use a textArea to paste it.

This would enable the configuration without relying on SSH

**Comment by mqtt-fan** [comment]
I adapted the changes

**Pull request merged**
