### PR TITLE
fix(utils): detect Buffer changes in KeyValueDeduplicationCache

### PR DESCRIPTION
**Pull request by 004helix**
## Type of change

Type A:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] UI Feature
- [ ] Refactor/Code Cleanup
- [ ] Docs
- [ ] Capability implementation for existing core capability
- [ ] New robot implementation
  
# Description (Type A)

Cache buffer data.
crc32 is too slow for this because it is a pure js code.
crypto's md5 implementation ~ 10-15 times faster for 10KB of buffer data

### CODE REVIEW

**Comment by Hypfer** [comment]
Out of curiosity, I did some benchmarks, because I remembered reading somewhere that somewhat unexpectedly, md5 was slower than SHA1. I've also added the current crc32 to the set of benchmarks

```
[root@p2028_release:/data]# PKG_EXECPATH=PKG_INVOKE_NODEJS /data/valetudo /data/hashbench_withcrc.js 
Starting benchmark with 10000 iterations and 131072 bytes payload size.
md5-hex: 8527.000ms total. 85ms per iteration. 0.664ms per kibibyte
md5-base64: 8491.000ms total. 84ms per iteration. 0.656ms per kibibyte
sha1-hex: 2222.000ms total. 22ms per iteration. 0.172ms per kibibyte
sha1-base64: 2225.000ms total. 22ms per iteration. 0.172ms per kibibyte
sha256-hex: 2408.000ms total. 24ms per iteration. 0.188ms per kibibyte
sha256-base64: 2373.000ms total. 23ms per iteration. 0.180ms per kibibyte
crc32: 133061.000ms total. 1330ms per iteration. 10.391ms per kibibyte
crc32-sha1-base64: 2368.000ms total. 23ms per iteration. 0.180ms per kibibyte
crc32-sha1-hex: 2380.000ms total. 23ms per iteration. 0.180ms per kibibyte
```

That is quite the difference.

<details>
<summary>Click here for the code</summary>

```js
const hash = require('crypto').createHash;
const randomBytes = require('crypto').randomBytes;
const hrtime = require("node:process").hrtime;

const crc = require("crc");

const size = 128*1024;
const iterations = 10000;
const scenarios = [
    { alg: 'md5', digest: 'hex' },
    { alg: 'md5', digest: 'base64' },
    { alg: 'sha1', digest: 'hex' },
    { alg: 'sha1', digest: 'base64' },
    { alg: 'sha256', digest: 'hex' },
    { alg: 'sha256', digest: 'base64' }
];


const data = randomBytes(size);

const scenarioRunners = {};



for (const { alg, digest } of scenarios) {
    scenarioRunners[`${alg}-${digest}`] = () => {
        hash(alg).update(data).digest(digest);
    }
}

scenarioRunners["crc32"] = () => {
    crc.crc32(data);
}
scenarioRunners["crc32-sha1-base64"] = () => {
    crc.crc32(hash("sha1").update(data).digest("base64"));
}
scenarioRunners["crc32-sha1-hex"] = () => {
    crc.crc32(hash("sha1").update(data).digest("hex"));
}


console.log(`Starting benchmark with ${iterations} iterations and ${size} bytes payload size.`);
for (const [name, runner] of Object.entries(scenarioRunners)) {
    const start = hrtime.bigint();

    for (let i = 0; i < iterations; i++) {
        runner();
    }

    const end = hrtime.bigint();
    const diff = end - start;

    const totalMs = Number(diff / BigInt(1000000));
    const singleMs = Number((diff / BigInt(iterations)) / BigInt(10000));
    const byteMs = singleMs / (size / 1024);

    console.log(`${name}: ${(totalMs).toFixed(3)}ms total. ${singleMs}ms per iteration. ${byteMs.toFixed(3)}ms per kibibyte`);
}
```

</details>

I also tried a shorter string payload that would simulate most of the messages stored:

```
[root@p2028_release:/data]# PKG_EXECPATH=PKG_INVOKE_NODEJS /data/valetudo /data/hashbench_string_withcrc.js 
Starting benchmark with 10000 iterations and 2048 characters payload size.
md5-hex: 767.000ms total. 7ms per iteration. 3.500ms per kibibyte
md5-base64: 657.000ms total. 6ms per iteration. 3.000ms per kibibyte
sha1-hex: 503.000ms total. 5ms per iteration. 2.500ms per kibibyte
sha1-base64: 478.000ms total. 4ms per iteration. 2.000ms per kibibyte
sha256-hex: 499.000ms total. 4ms per iteration. 2.000ms per kibibyte
sha256-base64: 499.000ms total. 4ms per iteration. 2.000ms per kibibyte
crc32: 8414.000ms total. 84ms per iteration. 42.000ms per kibibyte
crc32-sha1-base64: 667.000ms total. 6ms per iteration. 3.000ms per kibibyte
crc32-sha1-hex: 650.000ms total. 6ms per iteration. 3.000ms per kibibyte
```

And an even shorter one:

```
Starting benchmark with 10000 iterations and 254 characters payload size.
md5-hex: 392.000ms total. 3ms per iteration. 12.094ms per kibibyte
md5-base64: 276.000ms total. 2ms per iteration. 8.063ms per kibibyte
sha1-hex: 249.000ms total. 2ms per iteration. 8.063ms per kibibyte
sha1-base64: 255.000ms total. 2ms per iteration. 8.063ms per kibibyte
sha256-hex: 259.000ms total. 2ms per iteration. 8.063ms per kibibyte
sha256-base64: 257.000ms total. 2ms per iteration. 8.063ms per kibibyte
crc32: 1089.000ms total. 10ms per iteration. 40.315ms per kibibyte
crc32-sha1-base64: 389.000ms total. 3ms per iteration. 12.094ms per kibibyte
crc32-sha1-hex: 396.000ms total. 3ms per iteration. 12.094ms per kibibyte
```


<details>
<summary>Click here for the code</summary>

```js
const hash = require('crypto').createHash;
const randomBytes = require('crypto').randomBytes;
const hrtime = require("node:process").hrtime;

const crc = require("crc");

const size = 2048;
const iterations = 10000;
const scenarios = [
    { alg: 'md5', digest: 'hex' },
    { alg: 'md5', digest: 'base64' },
    { alg: 'sha1', digest: 'hex' },
    { alg: 'sha1', digest: 'base64' },
    { alg: 'sha256', digest: 'hex' },
    { alg: 'sha256', digest: 'base64' }
];


const data = randomBytes(size).toString("hex");

const scenarioRunners = {};



for (const { alg, digest } of scenarios) {
    scenarioRunners[`${alg}-${digest}`] = () => {
        hash(alg).update(data).digest(digest);
    }
}

scenarioRunners["crc32"] = () => {
    crc.crc32(data);
}
scenarioRunners["crc32-sha1-base64"] = () => {
    crc.crc32(hash("sha1").update(data).digest("base64"));
}
scenarioRunners["crc32-sha1-hex"] = () => {
    crc.crc32(hash("sha1").update(data).digest("hex"));
}


console.log(`Starting benchmark with ${iterations} iterations and ${size} characters payload size.`);
for (const [name, runner] of Object.entries(scenarioRunners)) {
    const start = hrtime.bigint();

    for (let i = 0; i < iterations; i++) {
        runner();
    }

    const end = hrtime.bigint();
    const diff = end - start;

    const totalMs = Number(diff / BigInt(1000000));
    const singleMs = Number((diff / BigInt(iterations)) / BigInt(10000));
    const byteMs = singleMs / (size / 1024);

    console.log(`${name}: ${(totalMs).toFixed(3)}ms total. ${singleMs}ms per iteration. ${byteMs.toFixed(3)}ms per kibibyte`);
}
```

</details>

So while crc32 is great for in-memory storage because it's so short, in its pure JS implementation, it's also very slow.
Much slower than I expected.

Probably the best solution would be to always do either `crc32(sha1-hex)` or `crc32(sha1-hex)`.


For reference, here are benchmark results on my laptop (`i5-8265U`)

```
Starting benchmark with 10000 iterations and 131072 bytes payload size.
md5-hex: 1835.000ms total. 18ms per iteration. 0.141ms per kibibyte
md5-base64: 1847.000ms total. 18ms per iteration. 0.141ms per kibibyte
sha1-hex: 1323.000ms total. 13ms per iteration. 0.102ms per kibibyte
sha1-base64: 1275.000ms total. 12ms per iteration. 0.094ms per kibibyte
sha256-hex: 2776.000ms total. 27ms per iteration. 0.211ms per kibibyte
sha256-base64: 2764.000ms total. 27ms per iteration. 0.211ms per kibibyte
crc32: 10910.000ms total. 109ms per iteration. 0.852ms per kibibyte
crc32-sha1-base64: 1312.000ms total. 13ms per iteration. 0.102ms per kibibyte
crc32-sha1-hex: 1332.000ms total. 13ms per iteration. 0.102ms per kibibyte
```

```
Starting benchmark with 10000 iterations and 2048 characters payload size.
md5-hex: 84.000ms total. 0ms per iteration. 0.000ms per kibibyte
md5-base64: 77.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha1-hex: 59.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha1-base64: 62.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha256-hex: 116.000ms total. 1ms per iteration. 0.500ms per kibibyte
sha256-base64: 110.000ms total. 1ms per iteration. 0.500ms per kibibyte
crc32: 722.000ms total. 7ms per iteration. 3.500ms per kibibyte
crc32-sha1-base64: 80.000ms total. 0ms per iteration. 0.000ms per kibibyte
crc32-sha1-hex: 80.000ms total. 0ms per iteration. 0.000ms per kibibyte
```

```
Starting benchmark with 10000 iterations and 254 characters payload size.
md5-hex: 32.000ms total. 0ms per iteration. 0.000ms per kibibyte
md5-base64: 26.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha1-hex: 24.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha1-base64: 25.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha256-hex: 32.000ms total. 0ms per iteration. 0.000ms per kibibyte
sha256-base64: 30.000ms total. 0ms per iteration. 0.000ms per kibibyte
crc32: 96.000ms total. 0ms per iteration. 0.000ms per kibibyte
crc32-sha1-base64: 36.000ms total. 0ms per iteration. 0.000ms per kibibyte
crc32-sha1-hex: 38.000ms total. 0ms per iteration. 0.000ms per kibibyte
```

**Comment by Hypfer** [comment]
> somewhat unexpectedly, md5 was slower than SHA1

Researching this further, it turns out that this isn't unexpected at all. There's hardware support for sha1 on both tested platforms

```
[root@p2028_release:~]# cat /proc/cpuinfo 
processor       : 0
BogoMIPS        : 48.00
Features        : fp asimd aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```


```
hypfer@crozier:~$ cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 142
model name      : Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
stepping        : 12
microcode       : 0xec
cpu MHz         : 1800.000
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sgx bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
vmx flags       : vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple pml ept_mode_based_exec
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs itlb_multihit srbds
bogomips        : 3600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

```

**Comment by Hypfer** [comment]
Welp. What I completely forgot is that my z10 is aarch64, while older robots are armv7.

I ran the same benchmark on my Roborock S5 and was suprised to see just how bad the performance is.
This likely means that the code needs to pick the right algorithm for the hardware its running on.

```
[root@rockrobo shm]# PKG_EXECPATH=PKG_INVOKE_NODEJS /usr/local/bin/valetudo bench.js 
Starting benchmark with 10000 iterations and 131072 bytes payload size.
md5-hex: 11046.000ms total. 110ms per iteration. 0.859ms per kibibyte
md5-base64: 10838.000ms total. 108ms per iteration. 0.844ms per kibibyte
sha1-hex: 17641.000ms total. 176ms per iteration. 1.375ms per kibibyte
sha1-base64: 17676.000ms total. 176ms per iteration. 1.375ms per kibibyte
sha256-hex: 32023.000ms total. 320ms per iteration. 2.500ms per kibibyte
sha256-base64: 31903.000ms total. 319ms per iteration. 2.492ms per kibibyte
crc32: 204469.000ms total. 2044ms per iteration. 15.969ms per kibibyte
crc32-sha1-base64: 18103.000ms total. 181ms per iteration. 1.414ms per kibibyte
crc32-sha1-hex: 18138.000ms total. 181ms per iteration. 1.414ms per kibibyte
```

I'll see what I can do. Thanks for bringing this issue to my attention

**Comment by 004helix** [comment]
crc32() is completely unnecessary here.
Since node has a Number.MAX_SAFE_INTEGER = 2^56-1 you can just use a first 52 bits of hash:
```js
    parseInt(hash(alg).update(data).digest("hex").substring(0, 13), 16);
```
This will have better collision protection than 32bit of crc32

Fixed a bit time calculations:
```js

    const totalMs = Number(diff / BigInt(1000000));
    const singleMs = totalMs / iterations;
    const byteMs = singleMs / (size / 1024);

    console.log(`${name}: ${totalMs}ms total. ${singleMs.toFixed(3)}ms per iteration. ${byteMs.toFixed(3)}ms per kibibyte`);

```

Added more algos:
```js
['md5', 'sha1', 'sha224', 'sha256', 'sha3-256', 'shake128', 'sm3'].forEach(alg => {
    scenarioRunners[`${alg}-first-52bits`] = () => {
        parseInt(hash(alg).update(data).digest("hex").substring(0,13),16);
    }
})
```

And here is result on rk3326:
```
[root@rk3326_64:~]# env PKG_EXECPATH=PKG_INVOKE_NODEJS /data/valetudo/valetudo /data/valetudo/hashbench_withcrc.js
Starting benchmark with 10000 iterations and 131072 bytes payload size.
md5-hex: 12711ms total. 1.271ms per iteration. 0.010ms per kibibyte
md5-base64: 12339ms total. 1.234ms per iteration. 0.010ms per kibibyte
sha1-hex: 5211ms total. 0.521ms per iteration. 0.004ms per kibibyte
sha1-base64: 5221ms total. 0.522ms per iteration. 0.004ms per kibibyte
sha256-hex: 5859ms total. 0.586ms per iteration. 0.005ms per kibibyte
sha256-base64: 5840ms total. 0.584ms per iteration. 0.005ms per kibibyte
crc32: 138651ms total. 13.865ms per iteration. 0.108ms per kibibyte
crc32-sha1-base64: 5770ms total. 0.577ms per iteration. 0.005ms per kibibyte
crc32-sha1-hex: 5608ms total. 0.561ms per iteration. 0.004ms per kibibyte
md5-first-52bits: 12517ms total. 1.252ms per iteration. 0.010ms per kibibyte
sha1-first-52bits: 5385ms total. 0.538ms per iteration. 0.004ms per kibibyte
sha224-first-52bits: 5911ms total. 0.591ms per iteration. 0.005ms per kibibyte
sha256-first-52bits: 5924ms total. 0.592ms per iteration. 0.005ms per kibibyte
sha3-256-first-52bits: 27934ms total. 2.793ms per iteration. 0.022ms per kibibyte
shake128-first-52bits: 23072ms total. 2.307ms per iteration. 0.018ms per kibibyte
sm3-first-52bits: 37980ms total. 3.798ms per iteration. 0.030ms per kibibyte
```

**Comment by Hypfer** [comment]
> Please don't close the PR without even giving the opportunity to respond

The PR was closed because it won't be merged as it is.
I will see if and how that problem will be solved whenever there is time to do so.

Please stop being this intrusive. We've discussed this before but it's still exactly the same.
This will be your final warning.

**Comment by Hypfer** [comment]
For reference:

    crc32() is completely unnecessary here.
    Since node has a Number.MAX_SAFE_INTEGER = 2^56-1 you can just use a first 52 bits of hash:

    This will have better collision protection than 32bit of crc32
 
 
Nope. It's not unnecessary. The 32 bit were chosen because they're shorter than 52 bits which is important when there are 200+ Topics that are being duplicated. As memory is quite sparse, we cannot waste that much on a feature that in itself is mostly unnecessary cosmetics.

Please take a step back and assume that everything you see in that codebase is there for a reason.
I've spend a _lot_ of time thinking about how they were built so if it looks like it's strange, chances are that you're simply missing context.

**Comment by Hypfer** [comment]
> Nope. It's not unnecessary. The 32 bit were chosen because they're shorter than 52 bits which is important when there are 200+ Topics that are being deduplicated. That's 62% more! As memory is quite sparse, we cannot waste that much on a feature that in itself is mostly unnecessary cosmetics.

I have to correct myself here. You're right.
As the value will in both cases always be a number, it will also always take up the same space in memory so indeed those 52 bits can be used to offer better collision protection

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/commit/269aa3004f3925e26afe66139109b201133afcfe

**Comment by Hypfer** [comment]
After having some time to think about this PR and the previous PR, I've figured out the issue with them.

With a bug fix, the decision that a thing should be like it is was already made in the past and it only turned out that apparently, the implementation was incorrect. With this change however, the string-only deduplication was intentionally built like that and did exactly what it was supposed to do.

Thus, this was a feature request and not bug fix. As such, the process of determining if and how it should be implemented should've been completely different.
Instead of starting with a full implementation as a PR, the first step would be to propose the idea, state why it would be desirable, state what other options have been considered, etc. Then, only after it has been decided that a thing should be implemented, a PR can be created.

This is why the whole thing felt very pushy. It completely bypassed the correct process by pretending to be something it wasn't.
I'm sorry that it take a while for me to understand this problem. I hope that in the future, I'll be able to fully understand these issues and provide better guidance quicker.

**Pull request closed without merging**
