### PR TITLE
Add ability to edit saved zones on map

### PR DESCRIPTION
**Pull request by matthiasharrer**
Although still work in progress, I wanted the to share the current state of editing saved zones using the map. (Zones-Tab -> Zone configuration -> Modify zones using map)

### CODE REVIEW

**Comment by matthiasharrer** [comment]
Current state:
Removed all coordinates based configuration and replaced it by simpler UI.
Goto Configuration is still missing..
Repetition of zones is also still missing 

improved-zone-selection

**Comment by cryptomilk** [comment]
Great work! This looks really promising.

**Comment by matthiasharrer** [comment]
It now also allows to define Goto Points.
It also adds some UI polishing like disabling the save button while the save request is ongoing to prevent multiple requests from happening.

Codequality-wise .. I think it perfectly fits the style of the index.html :)

**Comment by fenio** [comment]
When is this functionality going to be present in official release?
0.3.1 doesn't have anything like that.

**Pull request merged**
