### PR TITLE
feat(mqtt): Add vacuum error state description property

### LINKED ISSUE #816: Error description is missing in state payload
## Describe the bug

`error` key is missing in state payload. It contained error description in the last year.

### Vacuum Model

Gen 1

### Valetudo Version

2021.03.0

## Expected behavior

State payload should contain an error description.

## Additional context

This is continuation of  https://github.com/Hypfer/Valetudo/issues/622

### PR DESCRIPTION
**Pull request by Depau**
Closes #816

@definitio until the new release is out you can check the docs here: https://depau.github.io/Valetudo/pages/integrations/mqtt.html#error-description-error-

### CODE REVIEW

**Comment by Hypfer** [comment]
Does it though?

Unless I'm mistaken, this only adds another homie topic with the error description but no home assistant sensor

**Comment by Depau** [comment]
I forgot to git push 😂

**Comment by Depau** [comment]
Well no, actually I mixed up with another PR. I didn't implement any HA component because the new State API does not support error messages: https://www.home-assistant.io/integrations/vacuum.mqtt/#state-configuration

I'll just add it as a sensor.

**Comment by Depau** [comment]
Just to be sure, here I'm recycling the homie value topic and passing it as is to the home assistant component. The Homie topic will receive a plan string, do you think I have to wrap it into a JSON string?

from:

```js
                        autoconf: {
                            state_topic: prop.getBaseTopic(),
                            icon: "mdi:alert"
                        }
```

to


```js
                        autoconf: {
                            state_topic: prop.getBaseTopic(),
                            value_template: "{{ value | to_json }}", // or "\"{{ value }}\""
                            icon: "mdi:alert"
                        }
```

**Comment by Hypfer** [comment]
You should be able to just publish the string that is the error description with no value_template needed

**Comment by Depau** [comment]
In that case, it should be ready as soon as the CI build finishes.

**Pull request merged**
