### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by rimrul**
This should, if it works add the rudimentary dark mode toggle I mentioned in #368.
I still need to test this, though.

### CODE REVIEW

**Comment by rimrul** [comment]
I've updated the dark css using the [OnsenUI theme roller](https://onsen.io/theme-roller/?customize) and unintentionally semi-reverted the changes from 4ba4468. I'll readd those and squash the css commits into one. 

Do we also need to apply the 4ba4468 changes to `dark-onsen-css-components.min.css` and `onsen-css-components.min.css` for that change to actually work as intended?

**Comment by rimrul** [comment]
Apparently the theme roller generated a broken light theme instead. Not exactly what I was attempting to do.

**Comment by rimrul** [comment]
The sidebar switch works, but I'm not currently modifying the map colours and the theme selection does not survive a refresh.

It's a start, but there's room for improvement.

**Comment by Hypfer** [comment]
What about persisting the theme settings to local storage so that they survive a refresh?

Should be easy to do

**Comment by rimrul** [comment]
Yes, some kind of persistence would definitly be good. I'm just not sure what the best approach to this is.

#368 suggests an MQTT command (which implies a setting stored on the vacuum) and sunset/sunrise timers (I guess based on vacuum time, but could be based on client time).

But what about multiple users (client browsers) with different preferences? Maybe cookies/local storage/indexed db are a better choice.

There's also `prefers-color-scheme` media queries, which I'd consider the proper thing to respect, but those [don't play nicely with `privacy.resistFingerprinting` in Firefox.](https://bugzilla.mozilla.org/show_bug.cgi?id=1535189)

**Comment by rimrul** [comment]
Ok, I've thought about it some more and decided to go with local storage and 'prefers-color-scheme' media queries. I've decided the explicit choice for Valetudo overrides the more general media queries. 

I'll leave MQTT and timers to others in the future.

**Pull request merged**
