### PR TITLE
MockCarpetModeControlCapability

### PR DESCRIPTION
**Pull request by ccoors**
## MockRobot features

Type A:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor/Code Cleanup
- [ ] Docs
- [x] Capability implementation for existing core capability
- [ ] New robot implementation
  
Type B:
- [ ] New capability
- [ ] New core feature

# Description (Type A)

Adds the `MockCarpetModeControlCapability`

### CODE REVIEW

**Comment by alexkn** [comment]
Why do we need a persistent state?

**Comment by ccoors** [comment]
Well, for instance, the initial idea was that if you want to debug an issue that only occurs eg. when the robot is cleaning, the battery is < 50 % and the carpet detection is off, you only have to get your virtual robot into that state once. When you restart Valetudo the previous state is restored.

Idk if it is useful, it's up for discussion.

**Comment by alexkn** [comment]
For this I would not implement a dynamically saved state, but rather multiple config parameters in the implementationSpecificConfig, to bring the robot into a defined state on startup.

What do you think @Hypfer ?

Maybe you should split the PR, MockCarpetModeControlCapability is ok to merge.

**Comment by Hypfer** [comment]
+1 to that

**Comment by ccoors** [comment]
Yeah, you are right. Removed that second commit.

**Pull request merged**
