### PR TITLE
draw robot and charger (#106)

### PR DESCRIPTION
**Pull request by petabyteboy**

### CODE REVIEW

**Comment by matthiasharrer** [comment]
Does this work if the map is not flipped?

**Comment by petabyteboy** [comment]
Probably not, is that a user-changable option?

**Comment by matthiasharrer** [comment]
I'm not sure where it originates, but I think the API returns that flag because in some cases only the map is flipped but not the path.
I don't know in which case this happens though.

**Comment by petabyteboy** [comment]
I could add a new property to the path drawer that saves if the map is flipped or not, as it was set using setFlipped(), and use that to determine the angle correctly in both cases. Does that sound about right?

**Comment by matthiasharrer** [comment]
Yes either that or calculate the angle using already transformed coordinates.

**Comment by jubudu** [comment]
Hello, 
since V0.2.0 neither the robot nor the charger is shown in my map. Downgrading to V0.1.0 gives this nice feature back. 
Is this a bug in V0.2.0?
Kind regards and thanks for this awesome app!

**Comment by matthiasharrer** [comment]
I did not add drawing the charger and the robot when implementing the new map view. However @petabyteboy added it just in this pull request. You can grap the version currently on master as there is no new release so far and will have the robot & charger back.

**Comment by Hypfer** [comment]
image
I think the icons should also be scaled according to the zoomlevel

**Comment by matthiasharrer** [comment]
Although it is just a technical thing that it is not scaled right now, I actually like it because the icons are always clearly visible but don't cover the whole screen and get pixelated when zoomed in..

**Comment by Hypfer** [comment]
image
They do also get pixelated when zoomed in

**Comment by matthiasharrer** [comment]
That's true at some point.. but I don't think zooming into the map this far is interesting. Maybe we just need to limit the scaling :)

**Pull request merged**
