### PR TITLE
MQTT config defaults

### PR DESCRIPTION
**Pull request by ccoors**
## MQTT config defaults

Type A:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] UI Feature
- [ ] Refactor/Code Cleanup
- [ ] Docs
- [ ] Capability implementation for existing core capability
- [ ] New robot implementation

# Description (Type A)

Show the MQTT config defaults in the UI. Also, minor UX fix in Timers.

### CODE REVIEW

**Comment by Hypfer** [comment]
Are you sure that this doesn't save the defaults to the config?

**Comment by ccoors** [comment]
It does save them. Isn't it a bug when they change?

**Comment by Hypfer** [comment]
They shouldn't change but they also shouldn't be persisted on first save as that would be redundant

**Comment by ccoors** [comment]
Okay. I could set the default value as a placeholder for the text fields?

**Comment by Hypfer** [comment]
What about having a preview topic string somewhere which incorporates these values?

That would also be helpful for people that want to directly interact with MQTT.

Something like

**The MQTT Topic structure will look like this:**

`valetudo/BrownHardToFindSwallow/BatteryStateAttribute/level`

which live updates when editing the textfields maybe? Color coding to match the parameters to its text field could also be an option

**Comment by ccoors** [comment]
That does sound neat. Let's start with the placeholders though, I'll think about that preview thing ;)

image

**Pull request merged**
