### PR TITLE
Support changing MQTT settings in web UI

### PR DESCRIPTION
**Pull request by TheLastProject**
Screenshot_2020-04-29 Mi Robot Vacuum
Screenshot_2020-04-29 Mi Robot Vacuum(1)

Must say, the dev env is actually pretty nice :)

### CODE REVIEW

**Comment by Hypfer** [comment]
There should probably also be a way to apply that configuration.
As of now, enabling will only be in effect on the next reboot

We should at least have a hint about that because that will surely confuse users

**Comment by TheLastProject** [comment]
Oops, I completely forgot about that part...

**Comment by TheLastProject** [comment]
In the Telegram chat, it was discussed how to best apply the MQTT changes on runtime. Restarting only the MQTT part was considered the best solution, but this is not currently supported by the code.

Leaving this note here as it's a blocker for this to be merged.

**Comment by Hypfer** [comment]
Since enabling control of the MQTT Interface via the Webinterface is a larger change, I'd suggest that we just add a hint to the UI regarding the necessary reboot.

This is already a huge improvement. Especially since rebooting the robot doesn't necessarily require ssh access.

**Comment by TheLastProject** [comment]
How would you reboot the vacuum without SSH? Just hold the power button for several seconds?

**Comment by Hypfer** [comment]
Exactly. If the english voicepack it will respond with `Turning off` and turn off the LED after a few seconds.
Then you can simply turn it on again

**Comment by TheLastProject** [comment]
Done :)

**Pull request merged**
