### PR TITLE
Adds first version of zoom-/dragable map

### PR DESCRIPTION
**Pull request by matthiasharrer**
Hi,

thanks for this awesome project!

I just wanted to share the map / zoned cleanup thing I am working on.

Here is what it is so far:
- Only tested with the gridmap of the v1 vacuum
- A few static files inside the **/zone** path (not integrated with the main UI)
- You can select a point with one click or a zone with to clicks
- You can start goto / zoned_cleanup commands with the selected coordinates
- The map can be zoomed by mousewheel / pinch-to-zoom
- The map can be dragged around
- The map is updated every 3s which causes a noticable lag

I think it is far from finished/perfect both from a usability point as well as from a technical point, so maybe it should not be merged quite yet.
However it is already quite useful to me (I am using it regularly) and I would like to discuss how to improve it and how to maybe integrate it with other attempts like @WolfspiritM 's rework of the frontend (I would like to have some module management for the frontend instead of one big file to be honest).

I'm looking forward to the discussion :)

### CODE REVIEW

**Comment by dickesW** [comment]
@matthiasharrer 
Nice - could you write a little howto?  I would really like to test it. Already cloned and build with your matthiasharrer:map branch.
Thx

**Comment by matthiasharrer** [comment]
I can try to add some gifs this weekend to show how it is supposed to look. Until then .. here is the textbased "howto":

1. Build and deploy the application to your robot. (Stop the service, replace the binary, change the permissions (chmod +x) and restart the service.

2. Go to the URI / IP you reach valetudo on

3. append /zone to the uri

4. You should see a map view with two buttons at the bottom. The map view should display the same map as the main interface.

5. Tapping on the map should add red markers for goto/zones

6. When a marker is set you can click the corresponding button for goto/zoned cleanup

7. the robot hopefully moves where it should move :)

Please let me know if you could make it work.

**Comment by dickesW** [comment]
Works like charm :) Thx! 
Would be nice, if you could display the coordniates of the marker/box?  So it would be easy to transfer them into the UI .
Very cool feature! thx again.

**Comment by thundergreen** [comment]
Will this be merged 👍?

**Comment by matthiasharrer** [comment]
Hey,

I'm not sure if it is ready to be merged @thundergreen , but feel free to use it (and improve it).

Unfortunately I gave away my v1 and bought a v2 which I'm currently using unrooted with the new map features. So while I will definitly root it again and use it with dummycloud & valetudo, right now I cannot test / work on it.

@dickesW If you want to use define your saved zones you could maybe just add console.log()s and use it on a desktop browser with F12 Devtools 

Here is where the coordinates are calculated: https://github.com/matthiasharrer/Valetudo/blob/9f47e33c22b381f7e350fcfeeeee2c7dea181185/client/zone/vacuum-map.js#L194

**Comment by JohnRev** [comment]
Wonderful work, @matthiasharrer !
I have added a small box (basic styling for now) to display the coordinates of the selected points.
I added a pull request to your "map" branch: https://github.com/matthiasharrer/Valetudo/pull/1
Here are the changes: https://github.com/JohnRev/Valetudo/commit/a589cca72841b71b0beaaf5517322be8349bfa3b

**Comment by thundergreen** [comment]
Just to be sure. I cloned https://github.com/matthiasharrer/Valetudo/ repo.. then I made: git checkout map to change to map branch. After I ran those commands

```
git clone http://github.com/hypfer/Valetudo
cd Valetudo
npm install
./node_modules/.bin/pkg --targets latest-linux-armv7 --no-bytecode --public-packages=exif-parser,omggif,trim,prettycron .
```

It created Valetudo file. This one I just copy on the Vacuum right? I already have Valetudo running on it.

I don't need to re create the conf file right?

**Comment by matthiasharrer** [comment]
Yep you just need to stop the service and replace the binary. See also the updated readme -> #56

**Comment by cnrd** [comment]
Does this work on 001633 (The new map version)? As the /zone page is empty except for the buttons.

**Comment by thundergreen** [comment]
I don't get the append/zoned ..cannot get error

**Comment by thundergreen** [comment]
@matthiasharrer  will this be merged and are u still working on it? Would be a pity if this would not be implemented

**Comment by matthiasharrer** [comment]
Hey,

@cnrd I don't think it works with the new map version (just because the README.md says valetudo doesnt and its the data used)

@thundergreen It's not my decision but I think one could merge it as its just an additional page and improve it further on. Right now I don't have any improvements to come soon.

**Comment by Hypfer** [comment]
This is amazing. Commanding the robot just by clicking somewhere on the map feels like an RTS:

Thank you for your contribution 👍

**Pull request merged**
