### PR TITLE
Generalize MiioSockets to support both server and client versions

### PR DESCRIPTION
**Pull request by rumpeltux**
This is in preparation of an experimental feature in which Valetudo proxies whitelisted requests/responses to the real xiaomi cloud which is great for development and debugging.

### CODE REVIEW

**Comment by Hypfer** [comment]
This is not a good idea since it will bring more people to this project that certainly don't belong here at all. :/

It's Valetudo _or_ the cloud. We're not doing Valetudo + Cloud. I don't want these people here

**Comment by rumpeltux** [comment]
I understand your concerns to some degree, but that said for me this is a very valuable development tool that I wouldn’t want to miss. Maybe as a middle ground such support could live in another branch and not be enabled by default.

In any case the changes in this PR are general in nature, so we also don’t need to finish the discussion now.

**Comment by Hypfer** [comment]
I do agree that this is a helpful development tool but it also feels like pandora's box to me.

I'm certain that we'd see a fork which makes that happen and which also would further damage the name/brand/whatever you might call it Valetudo :/

**Comment by Hypfer** [comment]
I guess there's no point in refraining from merging a useful feature just because it could also be used in _bad_ ways.

Valetudos mission statement is very clear about the no cloud part so that should hopefully be sufficient.

**Pull request merged**
