### PR TITLE
firmware updates via webui

### PR DESCRIPTION
**Pull request by petabyteboy**
```
curl -d '{"md5": "84e93f212c1446d6a32894d87eabc6f7"}' --header "Content-Type: application/json" 172.44.0.101/api/upload_firmware_md5
curl --data-binary @v11_001748.fullos.pkg --header "Content-Type: application/octet-stream" 172.44.0.101/api/upload_firmware_update
curl 172.44.0.101/api/update_progress
curl 172.44.0.101/api/update_status
```

### CODE REVIEW

**Comment by olekenneth** [comment]
Why not send the md5 as a header?

**Comment by petabyteboy** [comment]
Great, idea. I'll try that.

**Comment by bruvv** [comment]
Any update on this :) ?

**Comment by petabyteboy** [comment]
Nope, but I would like to continue working on it at some point.

**Pull request closed without merging**
