### PR TITLE
Implement support for the viomi devices

### PR DESCRIPTION
**Pull request by rumpeltux**
viomi.vacuum.v7 uses a different API than roborock, so this required adding decoupling of Robot-specific things.

Current state of viomi support:

*   Reading basic status properties work, cloud & local connection work. Almost all Robot control functions are still broken, but should be easy to add once this patch lands.
*   Map upload is very experimental, fragile and incomplete.

This includes some refactorings to decouple the actual robot device.

*   A common interface class for Robots, implementation classes for Robots.
    * Includes a status interface, with string status codes instead of Roborock specific ints
*   Implementations share common code: `MiioSocket` is an abstraction for UDP protocol used by both cloud and local connection.

Since this project doesn’t have tests and I don’t have a Roborock, I cannot really regression test this. So I would very much welcome if the community could help with this, potentially fixing any regressions that were inadvertedly added.

Thank you!

### CODE REVIEW

**Comment by rimrul** [comment]
The modifications to README.md are probably not supposed to be merged like this.

The general concept looks good. The Model class looks like it could be nicely extended for #382 and similar things regarding mopping/persistent data.

I haven't looked at the details, though.

**Comment by Hypfer** [comment]
This is amazing! But how did you root it? I didn't know that it even exists

**Comment by rumpeltux** [comment]
I reverted the `README.md` modifications and fixed a few bugs after doing some more testing.
Let me know if there are any more concerns before merging.

**Comment by rumpeltux** [comment]
Merged this as discussed with Hypfer. I’ll keep an eye out for any new breakages (which hopefully won’t happen :-)).

**Comment by alexkn** [comment]
My valetudo crashes with your changes directly on startup:


```
Loading configuration file: /mnt/data/valetudo/config.json
sending HandshakePacket <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> 127.0.0.1 54321
mqtt start
Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
Webserver running on port 80
still waiting for handshake
sending HandshakePacket <Buffer 21 31 00 20 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff> 127.0.0.1 54321
still waiting for handshake
incoming message <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> null
incoming message <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> null
Connected successfully to mqtt server
still waiting for handshake
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":1}
still waiting for handshake
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":2}
request 1 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":1003}
request 2 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":2004}
request 1003 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":3005}
request 2004 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":4006}
request 3005 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":5007}
request 4006 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":6008}
request 5007 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":7009}
request 6008 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":8010}
request 7009 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":9011}
request 8010 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":10012}
request 9011 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_status","params":{},"id":11013}
request 10012 timed out
sending <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> 127.0.0.1 54321 {"method":"get_curpos","params":{},"id":12014}
incoming message <Buffer 56 78 53 33 38 30 6a 44 55 59 48 30 39 36 4e 63> {"result":[{"msg_ver":2,"msg_seq":2486,"state":2,"battery":81,"clean_time":672,"clean_area":10672500,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":1,"fan_power":1,"dnd_enabled":0}],"id":11013}
exiting...
/snapshot/Valetudo/lib/miio/MiioSocket.js:66
                pending.callback(msg['error'], msg['result']);
                        ^

TypeError: pending.callback is not a function
    at Socket.MiioSocket.socket.on (/snapshot/Valetudo/lib/miio/MiioSocket.js:66:25)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:673:8)

```

**Comment by rumpeltux** [comment]
Hey Alex, can you try with the viomi branch again to confirm that it doesn’t break master if we merge. Thanks!

**Comment by alexkn** [comment]
It does not crash on startup now
Start/Stop/Pause cleaning works.

But I have other issues:

Something is wrong with map updates.
Sometimes there are no updates.
Sometimes updates come after about a minute.

The drive HOME button does not work.

Settings->Persistant Data does not work:
Message: "Sorry .. only the RoboRock S5x supports the persistent map features."

**Comment by rumpeltux** [comment]
Thanks for the feedback Alex!

For the type-stuff, I filed #426. A core problem is that vscode doesn’t support ES5 inheritance which is the source for many of the problems.

I don’t think I touched Dummycloud.shutdown so the error there is nothing newly introduced. (I also don’t think it’s bad).

The other issues you mentioned should be fix. Please give it another try.
Thanks a lot!

**Comment by alexkn** [comment]
Map updates still don't work.

The drive HOME button works now.

Settings->Persistant Data works now.

I see some errors in the log:
```
(node:7231) UnhandledPromiseRejectionWarning: timeout
(node:7231) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7231) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It's repeating after some time.

**Comment by rumpeltux** [comment]
Could you share the logs with me?

**Comment by alexkn** [comment]
I'm sorry to say that, but I don't think this try and error procedure will work to get this done.

We should start with a more design-oriented approach.

For supporting different hardware, we need a hardware independent Interface between the valetudo components (webinterface, web api, mqtt) and the hardware dependend components (rockrobo, viomi, miio, dummycloud).
I don't see such an interface in your code yet.
Then we have to refactor the current implementation to implement that interface.
I can help with that.

Then you write a new implementation for viomi, without changing the interface.

**Comment by alexkn** [comment]
> Could you share the logs with me?

I don't want share my logs, too much private data in there.

**Comment by rumpeltux** [comment]
imho the problem is less the lack of interface, but rather the lack of tests. So when touching any code, there’s a risk of breakage. Consequently try & error is to some degree the only viable development approach.
To try to alleviate this at least partially I added the `fakerobot.js` tool to which valetudo can connect. To populate it, logs are required, but I understand if you don’t want to share them. If you can however, it would already help, if you were to add potentially missing commands to the tool so that errors you observe become reproducible. If the map stuff is still persisting after my last push, can you try to see from the logs what’s wrong? (e.g. is `get_map_v1` command getting send at all? is the dummycloud connection established? or is the robot not sending maps / is map parsing failing?)

I would also love to have that interface completely defined and working etc. But that’s a lot of work that I cannot do all at once, so incremental changes it must be. For the time being `MiioVacuum` is at least a step forward towards that interface.
The breakages were introduced due to the refactoring that tried to untangle some of the components. However, I do think that the codebase is in a strictly better state after these changes. So I would appreciate any help to get this into a complete working state again, rather than having two possibly diverging branches.
From there we can work to clarify the interface and perform further refactorings.

**Comment by rumpeltux** [comment]
If there are no further error reports, I’m going to merge this back into master to avoid creating diverging branches with too many merge conflicts.

**Comment by alexkn** [comment]
I haven't tested your latest changes.
The fact that nobody reports errors does not necessarily mean that everything works ...

**Comment by Hypfer** [comment]
Local communication breaks as soon as the robot connects to the cloud interface.
After the connect, every local request times out.

I guess one MiioSocket messes up the internal state of the other?

**Comment by alexkn** [comment]
I checked the error at shutting down:
```
[2020-02-16T10:25:39.535Z] [INFO] Valetudo shutdown in progress...
[2020-02-16T10:25:39.538Z] [DEBUG] Shutting down the MQTT Client...
[2020-02-16T10:25:39.560Z] [DEBUG] Shutting down the MQTT Client done
[2020-02-16T10:25:39.563Z] [DEBUG] Webserver shutdown in progress...
[2020-02-16T10:25:39.568Z] [DEBUG] Webserver shutdown done
[2020-02-16T10:25:39.571Z] [DEBUG] MiioVacuum shutdown in progress...
[2020-02-16T10:25:39.574Z] [DEBUG] cloud socket shutdown in progress...
[2020-02-16T10:25:39.578Z] [DEBUG] cloud socket shutdown done
[2020-02-16T10:25:39.579Z] [DEBUG] local socket shutdown in progress...
[2020-02-16T10:25:39.581Z] [DEBUG] local socket shutdown done
[2020-02-16T10:25:39.582Z] [DEBUG] MiioVacuum shutdown done.
[2020-02-16T10:25:39.585Z] [DEBUG] Dummycloud shutdown in progress...
[2020-02-16T10:25:39.589Z] [ERROR] Error occured:  Error [ERR_SOCKET_DGRAM_NOT_RUNNING]  -  Not running
[2020-02-16T10:25:39.592Z] [ERROR] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at Socket._healthCheck (dgram.js:652:11)
    at Socket.close (dgram.js:528:8)
    at Promise (/snapshot/Valetudo/lib/miio/Dummycloud.js:83:21)
    at new Promise (<anonymous>)
    at Dummycloud.shutdown (/snapshot/Valetudo/lib/miio/Dummycloud.js:75:12)
    at Valetudo.shutdown (/snapshot/Valetudo/lib/Valetudo.js:189:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-02-16T10:25:39.594Z] [INFO] exiting...
```

It is because the dgram.socket is closed twice.
Once in MiioSocket.shutdown() and once in DummyCloud.shutdown().
Since it is created in DummyCloud only DummyCloud should close it.

**Comment by rumpeltux** [comment]
Thanks! This should be fixed with e0681fa

**Comment by Hypfer** [comment]
While I haven't thoroughly tested the current state for multiple days _yet_, I can't find any obvious issues anymore.

What do you think @alexkn ?

**Comment by alexkn** [comment]
Seems like it works now.

**Pull request merged**
