### PR TITLE
supported-robots: Update Dreame W10 info with mapping pass and pin header quirks

### PR DESCRIPTION
**Pull request by USA-RedDragon**
## Type of change

Type A:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] UI Feature
- [ ] Refactor/Code Cleanup
- [x] Docs
- [ ] Capability implementation for existing core capability
- [ ] New robot implementation
  
Type B:
- [ ] New capability
- [ ] New core feature

# Description (Type A)

Right now, the mop pad mapping issue is undocumented and the pin header orientation as well. This should help ease some of the Telegram support burden for this mop.

### CODE REVIEW

**Comment by Hypfer** [comment]
While I see the idea behind that, I'd very much like to avoid bloating that overview section with information that is temporary in nature. Both of these things will hopefully become irrelevant with rooting method updates and a newer firmware version.

The reasoning behind that is twofold:
Not only do people simply tune out if faced with too much text, but as soon as information is out there on the public web, it is simply impossible to get rid of it again.
This means that there would always be this online rumor that you have to remove the mops on a W10 for a mapping pass even though it might've been fixed ages ago with a firmware update.


If we'd be sure that the W10 is EOL and would not receive a firmware update, it _may_ have been a different story, although even in that case, the docs would probably the wrong place for that information. Instead, Valetudo should just throw an error message if the mops are attached.


Anyway, while it might not always seem like it, a lot of thought went into the docs including which information to include or omit.

**Comment by USA-RedDragon** [comment]
k

**Comment by USA-RedDragon** [comment]
>  This means that there would always be this online rumor that you have to remove the mops on a W10 for a mapping pass even though it might've been fixed ages ago with a firmware update.

So instead, there's an online rumor that mapping doesn't work. Is that better?

**Comment by USA-RedDragon** [comment]
Also, the orientation of the connector is _not_ temporary information

**Pull request closed without merging**
