### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by alexkn**
as mentioned in #426 

including initial fixes
and GitHub Action to automatically lint commits

You can use the Visual Studio Code Extension "ESLint"
or you can run the linter manually with:
`npm run lint`

### CODE REVIEW

**Comment by rimrul** [comment]
Would it make sense to combine the CI job with the existing Travis CI? Looking at the Travis job it just seems to run 'npm build' in trusty. Github doesn't seem to offer trusty runners. So I guess if we merge them we'd need to merge them on trusty.

**Comment by alexkn** [comment]
I also wondered if I should merge that.
But as you've already noticed, there are no trusty runners on GitHub.

I am not sure if that job really has to run on trusty.
The build even works on windows.

I have never used Travis.
GitHub actions have the advantage that they also run in forks without any further configuration.

I would let the jobs run parallel for now.

**Comment by rimrul** [comment]
Ok, sounds like a solid plan. Testing on Trusty probably makes more sense than just building on trusty. I'll investigate if we could get a trusty-armv7 docker image going on github (using [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action) and a custom image) for when we have some tests. I don't think we'll get a tina linux container for Viomi CI, though.

**Comment by rumpeltux** [comment]
Tina Linux isn’t really required. I think the core params are armv6 or armv7 with musl libc. I believe the latter is covered by images labeled alpine.

**Comment by alexkn** [comment]
You should open a new issue for testing ideas.

**Pull request merged**
