### PR TITLE
live map

### PR DESCRIPTION
**Pull request by petabyteboy**

### CODE REVIEW

**Comment by petabyteboy** [comment]
TODO:
- investigate how to improve performance while map reloads
- reconnect automatically if connection breaks

**Comment by petabyteboy** [comment]
- Is the path from the map api used anywhere else or can I delete it?
- The header of MapFunctions says it is used in the client and the server, is there any example of how I can use it in the client? For now I just copied the logCoordToCanvasCoord function to vacuum-map.js.

**Comment by petabyteboy** [comment]
In the future we could also stream changed pixels of the map over the same websocket.

**Comment by cryptomilk** [comment]
Looks interesting!

**Comment by petabyteboy** [comment]
> * Is the path from the map api used anywhere else or can I delete it?
> * The header of MapFunctions says it is used in the client and the server, is there any example of how I can use it in the client? For now I just copied the logCoordToCanvasCoord function to vacuum-map.js.

I am still looking for answers to these questions @Hypfer @matthiasharrer 

Otherwise I have tested this on my robot for a while now and it is pretty reliable. I still want to look into some kind of interpolation or prediction, to make it even more smooth, but this could also be done in a separate PR. 

Feel free to give me feedback on the code :-)

**Comment by petabyteboy** [comment]
Some comments about dependencies:

I had to pick a websocket implementation. `ws` is a very lightweight websocket library for nodejs, and it doesn't try to provide any additional functionality we don't need (like emulating websockets over HTTP, websocket support is widely available in modern web browsers). It only has one subdependency. 
http://npm.anvaka.com/#/view/2d/ws

I decided to use a library to tail `SLAM_fprintf.log`. Implementing something similar to `tail -f` natively in nodejs is not so easy, and `tail` is a nodejs library which does exactly what we need, and it has no additional subdependencies.
http://npm.anvaka.com/#/view/2d/tail

**Comment by matthiasharrer** [comment]
I think it looks really cool.

I tested one version where for some reason valetudo crashed later that day but I'm not sure which version it was.

Regarding the path data I don't think its used somewhere else in the client @Hypfer?

Concerning the code I think it adds complexity as any feature does and the code for sure was not perfect in this area (or anywhere else). The only thing I'm not so sure about is that I tried to keep the data retrieval part out of the map code so far and just pass in the data. Also I'm bot sure if the frontend should know about the log file format or if parsing should be done on the server.

You also asked about the logCoordToCanvasCoord function .. but I can't see that you are actually calling it anywhere?

Keep up the nice work!

**Comment by Hypfer** [comment]
There is some server side drawing logic which is used by FHEM users that possibly uses the Path Data.
Does it handle reverse proxies gracefully?

I don't really have time to look at the code atm so review + merge might take a while. I do like your choice of libraries, though.

**Comment by petabyteboy** [comment]
Thanks for your comments. 

> I tested one version where for some reason valetudo crashed later that day but I'm not sure which version it was.

I had multiple crashes recently, some of which are definitely related to the new code, some of which should be fixed now. Let me list those here that still needs to be fixed:

```
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (watch for /dev/shm/SLAM_fprintf.log failed: Error: ENOENT: no such file or directory, stat '/dev/shm/SLAM_fprintf.log')
    at Tail.emit (events.js:171:17)
    at Tail.watch (/snapshot/Valetudo/node_modules/tail/lib/tail.js:128:12)
    at new Tail (/snapshot/Valetudo/node_modules/tail/lib/tail.js:79:10)
    at new WebServer (/snapshot/Valetudo/webserver/WebServer.js:872:18)
    at new Valetudo (/snapshot/Valetudo/Valetudo.js:27:22)
    at Object.<anonymous> (/snapshot/Valetudo/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:700:30)
    at Module._compile (pkg/prelude/bootstrap.js:1261:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
```

And then there's this crash I'm totally not sure if it's caused by the new code, and if there's no explanation how it could be caused by the new code I'd open an issue for it:

```
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/dev/shm/navmapfirst.ppm'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)
    at Object.fs.readFileSync (fs.js:485:33)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:679:36)
    at /snapshot/Valetudo/webserver/WebServer.js:1089:62
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:3)
```

> Concerning the code I think it adds complexity as any feature does and the code for sure was not perfect in this area (or anywhere else). The only thing I'm not so sure about is that I tried to keep the data retrieval part out of the map code so far and just pass in the data. Also I'm bot sure if the frontend should know about the log file format or if parsing should be done on the server.

That's a good point, I could move the parsing to the server, and stringify the parsed objects, to parse them as JSON on the other side. I will take another look at how that will affect parsing of "reset" statements.
I don't think it would remove any complexity, but it will be needed for advanced features like parsing the archive up to the last "reset" to deliver complete data.

> 
> You also asked about the logCoordToCanvasCoord function .. but I can't see that you are actually calling it anywhere?

You're completely right, I thought I needed it, but in the end I didn't, so removed it again.

**Comment by petabyteboy** [comment]
> There is some server side drawing logic which is used by FHEM users that possibly uses the Path Data.

Do you know what API endpoints they use? If I rewrite the websocket streaming to move parsing to the server, it might be possible to re-use a lot of this code and avoid having it twice in the project.

> Does it handle reverse proxies gracefully?

The websocket will work fine through reverse proxies as long as the reverse proxy can forward websockets.
Nginx needs some extra configuration for this: https://www.nginx.com/blog/websocket-nginx/

> 
> I don't really have time to look at the code atm so review + merge might take a while. I do like your choice of libraries, though.

I'm not in a hurry with merging this, quite the opposite, I think it should be thoroughly tested and stabilized before it is merged.

**Comment by petabyteboy** [comment]
So, I tried to move the parsing back to the server, but to be honest parsing the textfile is so easy that there is not much complexity to remove. The client has to deal with it's own data in some way to make streaming possible. Because the client has it's own storage of coordinates that gets updated incrementally, reset statements also have to be forwarded, so I ended up with a JSON serialization that is very similar to the textfile and requires similar parsing.

I still think this might save us some complexity in the future, so even if it seems a bit unnecessary at first, for example it gives us the possibility to only send the coordinates after the last reset statement to the client when it first connects. 

Next I want to, as I already mentioned in a previous comment, solve #84 by concatenating maps from the archive, until there is a reset statement, or there are no files left. To implement this, the server has to parse the files anyway.

**Comment by Hypfer** [comment]
After the robot returned to the dock, valetudo crashed:

`Mar  3 10:32:04 rockrobo kernel: [28178.082163] init: valetudo main process (3181) terminated with status 1
Mar  3 10:32:04 rockrobo kernel: [28178.082239] init: valetudo main process ended, respawning
Mar  3 10:32:07 rockrobo kernel: [28180.590777] init: valetudo main process (3324) terminated with status 1
Mar  3 10:32:07 rockrobo kernel: [28180.590844] init: valetudo main process ended, respawning
Mar  3 10:32:09 rockrobo kernel: [28183.261813] init: valetudo main process (3334) terminated with status 1
Mar  3 10:32:09 rockrobo kernel: [28183.261880] init: valetudo main process ended, respawning
Mar  3 10:32:12 rockrobo kernel: [28185.789458] init: valetudo main process (3398) terminated with status 1
Mar  3 10:32:12 rockrobo kernel: [28185.789526] init: valetudo main process ended, respawning
Mar  3 10:32:14 rockrobo kernel: [28188.429374] init: valetudo main process (3408) terminated with status 1
Mar  3 10:32:14 rockrobo kernel: [28188.429440] init: valetudo main process ended, respawning
Mar  3 10:32:17 rockrobo kernel: [28191.014307] init: valetudo main process (3500) terminated with status 1
Mar  3 10:32:17 rockrobo kernel: [28191.014374] init: valetudo main process ended, respawning
Mar  3 10:32:20 rockrobo kernel: [28193.613861] init: valetudo main process (3516) terminated with status 1
Mar  3 10:32:20 rockrobo kernel: [28193.613931] init: valetudo main process ended, respawning
Mar  3 10:32:22 rockrobo kernel: [28196.194611] init: valetudo main process (3578) terminated with status 1
Mar  3 10:32:22 rockrobo kernel: [28196.194678] init: valetudo main process ended, respawning
Mar  3 10:32:25 rockrobo kernel: [28198.789439] init: valetudo main process (3598) terminated with status 1
Mar  3 10:32:25 rockrobo kernel: [28198.789508] init: valetudo respawning too fast, stopped`

It won't start again :(

**Comment by petabyteboy** [comment]
can you get the output from /var/log/upstart/valetudo.log?

**Comment by leonardpitzu** [comment]
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (watch for /dev/shm/SLAM_fprintf.log failed: Error: ENOENT: no such file or directory, stat '/dev/shm/SLAM_fprintf.log')
    at Tail.emit (events.js:171:17)
    at Tail.watch (/snapshot/Valetudo-feature-live-map/node_modules/tail/lib/tail.js:128:12)
    at new Tail (/snapshot/Valetudo-feature-live-map/node_modules/tail/lib/tail.js:79:10)
    at new WebServer (/snapshot/Valetudo-feature-live-map/webserver/WebServer.js:872:18)
    at new Valetudo (/snapshot/Valetudo-feature-live-map/Valetudo.js:27:22)
    at Object.<anonymous> (/snapshot/Valetudo-feature-live-map/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:700:30)
    at Module._compile (pkg/prelude/bootstrap.js:1261:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)

**Comment by Hypfer** [comment]
Please rebase onto https://github.com/Hypfer/Valetudo/tree/cloud_map_upload

A lot of things have changed but everything should work much better now

**Comment by petabyteboy** [comment]
I'm currently in the hospital for a few weeks, but I should be able to test things remotely. I might take a while to continue here, so if anyone else wants to take over feel free to do so.

**Comment by cryptomilk** [comment]
Get well soon!

**Comment by Hypfer** [comment]
This has been integrated in the 0.3.0 Development branch

**Pull request closed without merging**
