### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by DeltaEvo**
This pull request is Draft for a new ui for Valetudo, there is not much yet, I'm opening it to start the discussion.

The current UI is great, but I think we can do better, my goal is to do responsive webapp and not only a mobile webapp, and with onsenUI it's seems harder, and seeing #90 (even if it's closed) you seems to be open for a refactor (?)

And with the new attribute logic I think we can try to do #551 alongside :)

Even if I want to add a desktop ui, I think we need to do it mobile first so I will start with the mobile ui and we will see later

So, first I want to give my personal thought on the current mobile ui, what I like and I want to keep:
- Having the status and the battery on the home page is a good thing
- The Map page is nice, zooming and panning is a must have
- The Dark and White theme is a good feature
- The Settings are well structured and intuitive

What i like less and I want to refactor or discuss about:
- There is a lot of buttons on the home page and some of them seems redundant: play/pause/stop, it look like a remote, and I think we should try to use the space on the home screen to show something else
- The Map page and the Zones pages seems to be redundant for me, this should only be one page
- The Manual Control is not very usable 
- Some of the settings could be presented why some better ui elements, for example a progress bar for the consumables
- The NavBar on the top is hard to access with the hand

This is not a fixed idea, but for now I think I will structure the ui like this:
  - Home Page:
    - The Status of the Robot (State, Battery)
    - A small view of the map to see the progress (+ Area and Time)
    - A Button to Start/Pause cleaning (if Started: Pause, else Start)
    - A Button to Stop/Dock robot (If Started or Paused: Stop, if Stopped: Dock, or maybe just remove stop ?)
    - Small buttons on the home page for navigation (Settings, Map) or a Navbar (I'm not sure yet, will try and see how it goes)
  - Map Page:
    - A Full screen map
    - A Edit button to edit rooms/zones, no-go zones/lines, and all what we need for the Map
 - Remote Control:
    - I don't know yet but I think if I do it It will be a virtual joystick
 - Settings Page:
    - All the current settings

For this new ui I will go with VueJS 2

I want to resolve the following issues: #379 #551 #109 #348 (Making it a PWA ?) and maybe more ?

I don't know yet if this should go in this repo or if @Hypfer you want to separate the UI and Valetudo it can go to another repo

Some resources for inspiration:
- https://dribbble.com/shots/6311150-Robot-Vacuum-Cleaner-App
- https://dribbble.com/shots/7047317-Smart-Home-App-Concept
- https://dribbble.com/shots/3374809-App-for-smart-vacuum-robot
- https://dribbble.com/shots/7729133-Shark-Robot-Map-Controls
- https://dribbble.com/shots/7784185-Shark-Selects
- https://www.youtube.com/watch?v=y1Hrsek0iQM
- https://www.youtube.com/watch?v=vEiUZzoXfPg
- https://www.youtube.com/watch?v=hhQnlEjZ_oA
- https://www.youtube.com/watch?v=bAeXkc8bhqE

### CODE REVIEW

**Comment by Hypfer** [comment]
I'll try to work through this line by line and add comments.
If I'm not commenting on something, assume that I agree with you.


> you seems to be open for a refactor (?)

Yes, definitely

>And with the new attribute logic I think we can try to do #551 alongside :)

I'm currently trying out some ideas regarding a capabilities system which would also include #551
There aren't any specifics yet though. That will take a few more days? weeks? Depending on time, mood etc.

The main big difference will be that not all robots provide the same controls. For example an S5 Max might have additional water pump controls which should not be displayed for a regular S5.
There will be standardized capabilities with vendor specific implementations and you should be able to get a list of all supported capabilities for this vacuum

Then you just build UI elements for each of those and display them if they are supported. That's definitely a must for the new UI

>The Dark and White theme is a good feature

Personally, I don't really care about the light theme and would be okay with a default and only dark theme to reduce complexity.

> some of them seems redundant: play/pause/stop

They are semantically different though. A pause is non-recoverable while a stop is. It may be possible to combine play/pause though. Unless I'm missing some edge-case.

> The Manual Control is not very usable

Personally I wouldn't really care if this was removed for the time being. It doesn't add any value imho.

Since the UI should be built around capabilities, the ManualControlCapability (working title) can and should follow at a later point in time.

>if Stopped: Dock, or maybe just remove stop ?

Nah. You might want to completely cancel the cleanup so you can run a new one without sending it back to the dock first.

> separate the UI and Valetudo it can go to another repo

I think that this should be the way to go


> Some resources for inspiration

Great examples! I really like the clean look of those dribbble concepts.
However I think that we should not oversimplify the UI just so that it looks clean.

If there are lots of features there have to be lots of controls. There's no way around that apart from reducing the amount of features. That's not something I'd want to do. Gnome 3 did that :/

**Comment by DeltaEvo** [comment]
> Then you just build UI elements for each of those and display them if they are supported. That's definitely a must for the new UI

Yep that what I was thinking to build the UI with this new capability system

> They are semantically different though. A stop is non-recoverable while a pause is. It may be possible to combine play/pause though. Unless I'm missing some edge-case.

I think also that we can at least combine play/pause, I understand that stop is a different action, but what i was thinking here is to combine some buttons so play with pause, or pause with stop (you pause first and you stop then) or stop with go to dock (your stop first then you go to dock [because when you go to dock this stop the current action] but IDK yet if it's a good idea x) ) to preserve some ui space since we have not a lot on a mobile UI

> I think that this should be the way to go

Ok so I think I will keep the pull request here to keep track of the changes and when it's ready we will see how to handle that (We can still extract all the commits and make another repo with git filter-branch :) )

> Great examples! I really like the clean look of those dribbble concepts.
However I think that we should not oversimplify the UI just so that it looks clean.

> If there are lots of features there have to be lots of controls. There's no way around that apart from reducing the amount of features. That's not something I'd want to do. Gnome 3 did that :/

> Both the first and the last example just waste like 50% of the screen with an image of the vacuum which serves no purpose apart from looking nice.

> So uh. Basically just take Form follows function as the basic design principle for Valetudo and everything should be fine

Yes I agree with that, I don't want to waste 50% of the screen space just for a vacuum cleaner image, I want to add more info on the home page, for me something that is missing is a better view of the progress, when I launch my vacuum robot I keep tracking where it is to try to see if it is stuck or if it moved in an awkward way (for me this means that something is in this path so I need to check) so I want to add a small view of the map and the current state like in the second dribble link

But in every case this pull request is here to discuss about the design so when I will try something I will post a screen or a link to view it here, so we can discuss and iterate on it :)

> So uh. Basically just take `Form follows function` as the basic design principle for Valetudo and everything should be fine
:+1:

**Comment by Hypfer** [comment]
Check out #584 for the updated REST api, capabilities system etc.

**Comment by tomaszpieczykolan** [comment]
Is this PR dead?

**Comment by DeltaEvo** [comment]
I didn't had the time to work on that but it's definitively something that I want to continue :)

**Comment by Hypfer** [comment]
Another thing that might be cool to have in the new UI would be some kind of demo mode where all API calls/responses are mocked.

**Comment by ccoors** [comment]
The capability system provides some abstraction over common functionality, but there are still some minor variations.

> Unfortunately, not all vendors support “stop”. If that’s not the case, stop will perform a pause.
> ~ Valetudo Docs

Maybe the capabilities themselves should "define" the UI. Then every implementation of said capability for every robot could generate the UI for the functions it provides. Maybe a new abstract method `getUIConfig` in the `Capability`-Class that returns a JSON, that the Frontend would parse and build a matching UI? Something like this (just an idea, mixed `BasicControlCapability` and `SpeakerVolumeControlCapability` for demonstration purposes):

```json
{
    "home": {
        "widgets": [
            {
                "type": "button",
                "icon": "play",
                "disabled": "state === cleaning (or maybe some more sophisticated inline scripting code?)",
                "label": "basic_control_clean_start",
                "onClick": [
                    {
                        "type": "put",
                        "payload": {"action": "start"}
                    },
                    {
                        "type": "reload_capability_state"
                    }
                ]
            }, { "type": "button", "...": "..." }
        ]
    },
    "settings": {
        "sound_settings": {
            "title": "sound_settings_title",
            "secondary_title": "sound_settings_title_secondary",
            "icon": "speaker",
            "widgets": [
                {
                    "type": "groupbox",
                    "label": "sound_settings_settings",
                    "widgets": [
                        {
                            "type": "slider",
                            "min": 0,
                            "max": 100,
                            "step": 5,
                            "value": "$this.volume ($this referring to this capability)"
                        },
                        {
                            "type": "button",
                            "label": "sound_settings_save_volume",
                            "onClick": [
                                {
                                    "type": "put",
                                    "payload": {"action": "set_volume", "volume": "$this.volume"}
                                },
                                {
                                    "type": "reload_capability_state"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    }
}
```

Maybe even go one step further further and invent Valetudo-Capabilities which also generate these UI-Definitions (for stuff like MQTT-Config, that access control config, ...). That would make it much easier to adapt the UI.

I am not sure on how to implement the map stuff though (like the MapSegmentEditCapability). Those might still need to be semi-hardcoded (maybe with custom widgets?) in the Frontend.

**Comment by csicar** [comment]
Some way to help on this PR? What would be needed to complete the PR?

**Comment by Hypfer** [comment]
@csicar take a look at https://github.com/Jomik/Valetudo-UI

**Comment by csicar** [comment]
Is there a plan to merge Valetudi-UI that back into this repo?

**Comment by Hypfer** [comment]
Probably at some point. It's currently in a very early development stage

**Comment by csicar** [comment]
Alright, thanks! I'll contribute to that project then :)

**Pull request closed without merging**
