### PR TITLE
Issue 255 Fan Power matches only exact values, other values show undefined in GUI

### PR DESCRIPTION
**Pull request by sklerotraficon**
This PR resolves the issue described in #255

### CODE REVIEW

**Comment by Hypfer** [comment]
Shouldn't it show the value itself instead of the closest one available?

**Comment by sklerotraficon** [comment]
I'm not really sure, what you mean, the current fan power is afaik never displayed in the GUI, only the preset labels.

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/pull/257/files#diff-7f958a715ef0d644371ae8b1b5f18250R487

This maps a fanspeed which isn't the preset to the preset?

**Comment by sklerotraficon** [comment]
Is it the method's naming that your comment is about ? Thnx for being a little more specific!

**Comment by Hypfer** [comment]
Nah.

We should show the real fanspeed value as a number if it isn't a preset instead of mapping it to the nearest valid preset which I assume the code I've referenced is doing.

Haven't tested it, though. That's why it might've been confusing

**Comment by sklerotraficon** [comment]
Yes, that was my intention:

If the fanpower value is lower or equal the threshold in the preset, use the preset threshold's label:

Example: 
Fanpower value greater than 38 and lower or equal 60 is showing "Balanced".

I actually like the presets, but there are options completely without them:

1. Fanpower Value only, eg. 50
2. Fanpower in Percent, eg. 50%
3. Volume-like control

Otherwise, with presets, it could be confusing to have both, numeric and presets on the button... don't you think?

**Comment by Hypfer** [comment]
The problem with this approach is that the UI just lies, because the fan speed is in fact not Balanced but rather something inbetween. This is imo worse than just showing undefined.

However I understand your point. I'd suggest showing something along the lines of `Custom: 50%`

**Comment by sklerotraficon** [comment]
Updated the PR:

If the value is not exactly matching the exact value from the preset, then the following is displayed:

Custom [fanpower]%

**Pull request merged**
