### PR TITLE
Update deployment instructions

### PR DESCRIPTION
**Pull request by cryptomilk**
Update deployment instructions for dummycloud functionality in Valetudo.

### CODE REVIEW

**Comment by Hypfer** [comment]
Can you also update the dustcloud imagebuilder to use this? Then I should be able to finish the new manual

**Comment by cryptomilk** [comment]
That's what I plan to do next. Do you plan to do a release before merging the map uploading feature?

**Comment by cryptomilk** [comment]
If not, we need:

```
+    # UPLOAD_METHOD   0:NO_UPLOAD    1:FTP    2:FDS
+    sed -i -E 's/(UPLOAD_METHOD=)([0-9]+)/\10/' $IMG_DIR/opt/rockrobo/rrlog/rrlog.conf
+    sed -i -E 's/(UPLOAD_METHOD=)([0-9]+)/\10/' $IMG_DIR/opt/rockrobo/rrlog/rrlogmt.conf
```

**Comment by Hypfer** [comment]
The next release should contain the map upload feature.
Since that can cause a lot of miio.log writes, we also need to patch `/opt/rockrobo/watchdog/ProcessList.conf` and change -l 2 to -l 0

**Pull request merged**
