### PR TITLE
Fix Viomi status & pause handling that was broken by eb6bece2

### PR DESCRIPTION
**Pull request by rumpeltux**
Addresses broken status handling (#591 & #594)

Don’t merge this as is. We’ll need a solution first how to handle different vendor-specific logic in `buttonStateMap` (see changes in home.js).

### CODE REVIEW

**Comment by Hypfer** [comment]
What about the `resumable` status flag?

https://github.com/Hypfer/Valetudo/blob/ae799a8f4a001120ba2cc34690e1fdef37c07b6d/lib/entities/state/attributes/StatusStateAttribute.js#L48-L55

Can we use that to handle the differences for viomi? It's already used for vendor oddities for roborock as seen here:

https://github.com/Hypfer/Valetudo/blob/ae799a8f4a001120ba2cc34690e1fdef37c07b6d/lib/devices/Roborock.js#L253-L277

**Comment by rumpeltux** [comment]
Sounds good :+1: 

Is there a reason that a state transition from "cleaning" to "start cleaning something else" is disallowed in the UI?
Even if the robot would not directly support this, Valetudo could just issue a "stop" command first before starting the next cleaning, right?

**Comment by Hypfer** [comment]
There's no technical reason for that limitation.

Since that is a "destructive" (the robot forgets its progress) action, I thought that it makes sense to require explicit confirmation to do so

**Comment by rumpeltux** [comment]
To confirm for Roborock:
in state "paused" the stop command should be disabled?
(for viomi it will clear any resumable status and make sure that a subsequent start button press starts a full clean)

Ok I’ll leave the default: stop first then do something else then.

Pausing the "return home" operation doesn’t seem to make too much sense (I also don’t see a resume for that implemented in RR, so I’ll keep the pause button disabled in that case.

**Comment by rumpeltux** [comment]
Also on second thought: I don’t get the `resumable` flag idea, shouldn’t this just be the state `paused`?

In any case I have a hard time mapping the viomi current operation selection into the StatusStateAttribute, because that’s created / updated at other random places. I’ll keep it as is for now.
It may make sense to introduce a separate state attribute that just captures the last started / current operation?

**Comment by Hypfer** [comment]
I just tested it with my S5.
Apparently it is possible to stop from a paused state. This causes a transition into the `idle` state which makes sense.

No idea why I've disabled the stop button for that state.

As for pausing the return home command:
For roborock, it can be resumed by calling the return home command again.
It will say "continue returning to the dock" instead of "going back to the dock" so it does know about that.
However I don't see any difference in behaviour so we might as well just ditch that completely


> Also on second thought: I don’t get the resumable flag idea, shouldn’t this just be the state paused?

While that is true most of the time, for roborock there can also be retuning/resumable and docked/resumable which happens when the robot isn't able to finish the cleanup on one full charge of the battery and then returns to continue later.

Maybe resumable is a bad name for it? 🤔

> It may make sense to introduce a separate state attribute that just captures the last started / current operation?

Sounds reasonable. That would also be a better match for what the resumable flag currently represents.
So we would have the immidiate state of the robot (cleaning, returning, docked, etc) and logic-wise on top of that some kind of task that it is trying to achive?

**Comment by rumpeltux** [comment]
Sorry I don’t have a lot of time to do the refactoring required for capturing the current command into an Attribute.
I’ll keep this on my radar, but want to get the fix in for now to avoid people getting frustrated about broken functionality.
I reinstated the pause functionality for returning-to-dock.

**Comment by rumpeltux** [comment]
I’ll close this for now as this isn’t really mergable to the Capabilities rewrite.

**Comment by rumpeltux** [comment]
Still cc @Depau in case the old reference helps you with your implementation.

**Pull request closed without merging**
