### PR TITLE
Add zoned cleanup, go to, spot clean and sound volume configuration

### PR DESCRIPTION
**Pull request by maxpautsch**
I added the following functionalities:
- zoned cleanup
- go to
- sound volume configuration
- spot clean
In order to use zoned cleanup and the go to functionality, i introduced a config file. See README.md.

### CODE REVIEW

**Comment by maxpautsch** [comment]
The defined zones and go to locations can be selected at the home screen home

**Comment by Hypfer** [comment]
Please move the config.json to /etc/valetudo/config.json and add code which creates it if it doesn't already exist. /usr/local/bin is no place for a config file
Also, a comment explaining Vacuum.prototype.startCleaningZone would be nice since I have no idea why that for loop exists.

Everything else looks fine. Thank you for your contribution

**Comment by maxpautsch** [comment]
Tested on target and it works.

**Comment by Hypfer** [comment]
The goto feature is incredibly useful for servicing the robot since I've placed the dock right under the couch.

Thanks 👍

**Pull request merged**
