### PR TITLE
Improved timer ui

### PR DESCRIPTION
**Pull request by Bennedetto**
Changed timer ui and added some features:
- UI does now seperate between cleaning and dnd timer
- UI does now allow easy configuration of cleaning timer
- UI does now allow configuration of timezone (fixes https://github.com/Hypfer/Valetudo/issues/42)

image

image

image

Tested on Gen2 robots - I do not have any possibility to test it on Gen1 bots, so if *you* have the possibility to test, please do so and let me know if it worked properly.

### CODE REVIEW

**Comment by stefanct** [comment]
Good work @Bennedetto! One thing I still miss is a way to edit existing timers. With these changes it is still only possible to disable or delete existing timers and not modify them.

**Comment by CodeFinder2** [comment]
Hi, I tried this on my gen1 with valetudo v0.4.0 and it's not working:

https://ibb.co/hV5cVP8
https://ibb.co/SyxjtyZ

Any other way to do this? Can I fix this to make it working on my gen1?

**Comment by stefanct** [comment]
Did you reboot the system after the change? I am not 100% sure it is needed but would not be surprised at all.

**Comment by CodeFinder2** [comment]
Just rebooted, no changes... 😕

**Comment by CodeFinder2** [comment]
Okay, wait might got something wrong: I assumed changing the timezone also changes the Setting > Info > Timezone data. Is that correct? If I change the timezone there, it stays changed in that dropdown box but it is not changed under Settings > Info.... 🙈 

I just followed [this tutorial](https://github.com/dgiese/dustcloud/wiki/Vacuum-Robots-CCC-to-CE-conversion) to make my CCC gen1 a CE gen1 and now it correctly says "Europe/Berlin" under Settings > Info. However, timezone settings in "Timers" are (still) not reflected in Settings > Info. Is that intended?

But can confirm for my gen1 that changing the timezone under "Timers" changes the timezone (only) there correctly (also persistent after a reboot). 😊👍

**Pull request merged**
