### PR TITLE
Support for mqtt state component in future HA

### PR DESCRIPTION
**Pull request by pszafer**
Added state_topic, support for state string and removed those case.

### CODE REVIEW

**Comment by pszafer** [comment]
It will be valid from HA 0.93.

----
Note for myself.
I need rename support `turn_on` to `start`

**Comment by bruvv** [comment]
how is this going?

**Comment by oechslein** [comment]
The fan speed 105 / mop is not handled in this code.

**Comment by pszafer** [comment]
Was it supported in earlier versions?

**Comment by oechslein** [comment]
> Was it supported in earlier versions?

You are now able to set "mop"/105 after https://github.com/Hypfer/Valetudo/pull/213 was merged (some days ago). So I assume "FAN_SPEED_TO_STRING[statusData.fan_power]" would then fail, or?
Before your change "mop" wasn't explicitly supported in mqtt. The default branch would have caught it and it would send a "105".

**Comment by pszafer** [comment]
It's different story...
This PR https://github.com/Hypfer/Valetudo/pull/213 added mop only for webui, not mqtt vacuum, that is the reasony why I didn't see it before.
I will create another PR for that.

**Pull request merged**
