### PR TITLE
fix(ui): Fix light mode

### PR DESCRIPTION
**Pull request by ccoors**
## Fix light mode in new UI

Type A:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] UI Feature
- [ ] Refactor/Code Cleanup
- [ ] Docs
- [ ] Capability implementation for existing core capability
- [ ] New robot implementation
  
Type B:
- [ ] New capability
- [ ] New core feature

# Description (Type A)
Light mode was disabled because some text was not readable. Fixed the text color by making it `textSecondary` color.

image

### CODE REVIEW

**Comment by Hypfer** [comment]
image


It wasn't just about the font though. The progress bar base also needs to pick up the light mode color as can be seen on the regular progress bars below

**Comment by ccoors** [comment]
Ah right. I'll take another look.

**Comment by ccoors** [comment]
@Hypfer Sure? Looks fine for me rn.

image

**Comment by Hypfer** [comment]
The system load progress bars are fine as they are just mui components

The ratio bar however has the dark theme color hardcoded:
https://github.com/Hypfer/Valetudo/blob/6777f3aa7bbf4ef5afea5a3ba8fdecd2aa8f150e/frontend/src/components/RatioBar.module.css#L7

**Pull request merged**
